domain:
  r_start: 0.05 # Percent of drive radius to use.
  r_end: 1
  num_points: 512
  dealiasing_factor: 1.5
  dt: 0.0001
  end_t: 0.1
background:
  beta_at_0: 0.05
  beta_at_R: 0.01
free:
  nondimenensionalization: 1
  solver: 'RK222'
initialization:
  velocity_magnitude: 3 # Calculated from nondimensionalization notebook.
  boundary_position: 0.95
  boundary_thickness: 0.02
experiment:
  R_helmholtz: 2.035 # m
  L_helmholtz: 2.33 # m (Distance between center of two coils since not actually helmholtz coil)
  R_drive: 0.92 # m
  B_H_at_0: 0.005 # T
  temperature: 8.01088317e-19 # J